name: Parameters_JSON

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'All configuration settings in JSON format'
        required: true
        type: string
        # default: '{"terraform_action":"apply","aws_account":"dev1","s3_bucket":"ec2-glue-athena-test","dynamodb":"statelock-tf","aws_region":"us-east-1","vpc_name":"hari_network","vpc_cidr":"10.1.0.0/16","pub_subnet_cidr":"10.1.3.0/24,10.1.4.0/24","pri_subnet_cidr":"10.1.1.0/24,10.1.2.0/24","EIP":false}'
        default: '{"s3_bucket":"ec2-glue-athena-test", "bucket_key":"tfstate","dynamodb_table":"statelock-tf","aws_region":"us-east-1","vpc_name":"hari_network","vpc_cidr":"10.1.0.0/16","pub_subnet_cidr":"10.1.3.0/24,10.1.4.0/24","pri_subnet_cidr":"10.1.1.0/24,10.1.2.0/24","EIP":false}'
      
      terraform_action:
        description: 'Incase pipeline fails kindly please destroy the resources and start from fresh'
        required: true
        default: apply 
        type: choice
        options:
        - apply
        - destroy
        
      aws_account:
        description: 'AWS Accounts'
        required: true
        type: choice
        options:
        - dev1
        - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.aws_account }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.9.2'

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ fromJson(github.event.inputs.config).aws_region }}

      - name: Create .tfvars file
        working-directory: /home/runner/work/tf_actions/tf_actions
        run: |
          CONFIG_JSON='${{ github.event.inputs.config }}'
          # Extracting individual values from JSON
          vpc_name=$(echo $CONFIG_JSON | jq -r '.vpc_name')
          vpc_cidr=$(echo $CONFIG_JSON | jq -r '.vpc_cidr')
          pub_subnet_cidr=$(echo $CONFIG_JSON | jq -r '.pub_subnet_cidr')
          pri_subnet_cidr=$(echo $CONFIG_JSON | jq -r '.pri_subnet_cidr')
          EIP=$(echo $CONFIG_JSON | jq -r '.EIP')
          aws_region=$(echo $CONFIG_JSON | jq -r '.aws_region')

          # Remove existing terraform.tfvars file and print working directory
          rm -rf ./terraform.tfvars && pwd

          # Write new values to terraform.tfvars
          echo "vpc_name  = \"$vpc_name\"" > ./terraform.tfvars
          echo "vpc_cidr = \"$vpc_cidr\"" >> ./terraform.tfvars

          # Handle public subnet CIDRs
          IFS=',' read -ra PUB_SUBNETS <<< "$pub_subnet_cidr"
          echo "pub_subnet_cidr = [$(printf '\"%s\",' "${PUB_SUBNETS[@]}" | sed 's/,$//')]" >> ./terraform.tfvars

          # Handle private subnet CIDRs
          IFS=',' read -ra PRI_SUBNETS <<< "$pri_subnet_cidr"
          echo "pri_subnet_cidr = [$(printf '\"%s\",' "${PRI_SUBNETS[@]}" | sed 's/,$//')]" >> ./terraform.tfvars

          echo "EIP = \"$EIP\"" >> ./terraform.tfvars
          echo "aws_region = \"$aws_region\"" >> ./terraform.tfvars

          # Display the contents of the terraform.tfvars file
          cat ./terraform.tfvars

      - name: Create backend.conf file
        run: |
          CONFIG_JSON='${{ github.event.inputs.config }}'
          # Extracting individual values from JSON
          key=$(echo $CONFIG_JSON | jq -r '.bucket_key')
          bucket=$(echo $CONFIG_JSON | jq -r '.s3_bucket')
          region=$(echo #CONFIG_JSON | jq -r '.aws_region')
          dynamodb=$(echo $CONFIG_JSON | jq -r '.dynamodb_table')

          echo "key = \"$key\"" >> .backend.tfvars
          echo "bucket = \"$bucket\"" >> ./backend.tfvars
          echo "region = \"$region\"" >> ./backend.tfvars
          echo "dynamodb_table = \"$dynamodb\"" >> ./backend.tfvars
          cat ./backend.tfvars

      - name: Terraform Init
        working-directory: /home/runner/work/tf_actions/tf_actions
        # if: ${{ github.event.inputs.terraform_action }} == 'apply'
        run: terraform init -backend-config=./backend.tfvars
      - name: Terraform Validate
        working-directory: /home/runner/work/tf_actions/tf_actions
        # if: ${{ github.event.inputs.terraform_action }} == 'apply'
        run: terraform validate
      - name: Terraform Destroy
        working-directory: /home/runner/work/tf_actions/tf_actions
        if: ${{ github.event.inputs.terraform_action  == 'destroy' }}
        run: terraform destroy -auto-approve
      - name: Terraform Plan
        working-directory: /home/runner/work/tf_actions/tf_actions
        if: ${{ github.event.inputs.terraform_action  == 'apply' }}
        run: terraform plan
      - name: Terraform Apply
        working-directory: /home/runner/work/tf_actions/tf_actions
        if: ${{ github.event.inputs.terraform_action  == 'apply' }}
        run: terraform apply -auto-approve