name: DeployTerraformConfiguration

on:
  workflow_dispatch:
    inputs:
      aws_account:
        description: 'AWS Account Numbers'
        required: true
        # default: '058264181012' # Default AWS Account
        type: choice
        options:
        - 058264181012_account_name
        - 018264181012
        - 028264181045
        - 038264181012
        - 048264181012
        - 068264181012
        - 078264181012
        - 088264181012
        - 098264181012
        - 011264181012
        - 012264181012
        - 012333181012
        - 013133181012
        - 014264181012
        - 015264181012
        - 016264181012
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev1
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.0.0'

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets[format('AWS_ACCESS_KEY_ID_{0}', inputs.aws_account)] }}
        aws-secret-access-key: ${{ secrets[format('AWS_SECRET_ACCESS_KEY_{0}', inputs.aws_account)] }}
        aws-region: us-east-1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        TF_VAR_aws_account: ${{ github.event.inputs.aws_account }}
