name: Deploy Terraform Configuration

on:
  push:
    branches:
      - dev1
  workflow_dispatch:
    inputs:
      aws_account:
        description: 'AWS Account Number'
        required: true
        default: '058264181012' # Default AWS Account

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev1
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.0.0'

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets['AWS_ACCESS_KEY_ID_' + inputs.aws_account] }}
        aws-secret-access-key: ${{ secrets['AWS_SECRET_ACCESS_KEY_' + inputs.aws_account] }}
        aws-region: us-east-1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        TF_VAR_aws_account: ${{ github.event.inputs.aws_account }}
